"""empty message

Revision ID: fc6bac8b7f08
Revises: ca6367422243
Create Date: 2026-07-16 18:21:58.761528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6bac8b7f08'
down_revision: Union[str, Sequence[str], None] = 'ca6367422243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplace_profile', 'first_name')
    op.drop_column('marketplace_profile', 'last_name')
    op.drop_column('marketplace_profile', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplace_profile', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('marketplace_profile', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('marketplace_profile', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
